require(devtools)
Sys.setenv("PKG_CXXFLAGS"="-std=c++11")
setwd(system.file("example", package="txtutils"))
countlines("test.assoc.linear")
fileExists("test.assoc.linear")
ncols("test.assoc.linear")
readcol("test.assoc.linear", 3, 1, 5)
x = readplinkoutr(filename = "test.assoc.linear", colnameSelect = c("SNP", "TEST", "P"))
