# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countlines <- function(fn) {
    .Call('txtutils_countlines', PACKAGE = 'txtutils', fn)
}

fileExists <- function(name) {
    invisible(.Call('txtutils_fileExists', PACKAGE = 'txtutils', name))
}

ncols <- function(fn) {
    .Call('txtutils_ncols', PACKAGE = 'txtutils', fn)
}

printlines <- function(fn) {
    invisible(.Call('txtutils_printlines', PACKAGE = 'txtutils', fn))
}

readcol <- function(fileName, colNum, nSkip, maxRowNum) {
    .Call('txtutils_readcol', PACKAGE = 'txtutils', fileName, colNum, nSkip, maxRowNum)
}

readcols <- function(fn, colsel, nFirstSkipLines, nSkipUnit) {
    .Call('txtutils_readcols', PACKAGE = 'txtutils', fn, colsel, nFirstSkipLines, nSkipUnit)
}

